name: basic

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt

    - name: Format with Black
      working-directory: src
      run: black .

    - name: Lint with flake8
      working-directory: src
      run: flake8

    - name: Test with PyTest
      working-directory: src
      run: python -m pytest
